routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cache-clear', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    return Redirect::to('/');
});

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('logout', function () {
    Auth::logout();
    return Redirect::to("/login")
      ->with('message', array('type' => 'success', 'text' => 'You have successfully logged out'));
});

Route::get('/', function () {
    Auth::logout();
    return Redirect::to("/login")
      ->with('message', array('type' => 'success', 'text' => 'You have successfully logged out'));
});
 
Route::get('/home', 'UserController@index')->name('/');


Auth::routes();

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware(['guest'])->name('password.request');

Route::post('/forgot-password', 'ForgotPasswordController@sent_reset_email')->middleware(['guest'])->name('password.email');

Route::get('/password/reset/{token}', function ($token) {
    return view('auth.reset-password', ['token' => $token]);
})->middleware(['guest'])->name('password.reset');

Route::post('/reset-password', 'ForgotPasswordController@reset_password')->middleware(['guest'])->name('password.update');

Route::get('/roles', 'RoleController@index')->name('roles');

Route::any('users', 'UserController@index')->name('users.index');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('products', 'ProductController');
});

Route::get('impersonate/{user_id}', 'RoleController@impersonate');
Route::get('impersonate_leave', 'RoleController@impersonate_leave');

##=================== Company Routes Start ==========================##

Route::any('companies', 'CompanyController@index')->name('companies.index');
Route::get('companies/create/{company?}', 'CompanyController@create')->name('companies.create');
Route::post('companies/store', 'CompanyController@store')->name('companies.store');
Route::get('companies/show/{company}', 'CompanyController@show')->name('companies.show');
Route::get('companies/edit/{company}', 'CompanyController@edit')->name('companies.edit');
Route::post('companies/update/{company}', 'CompanyController@update')->name('companies.update');
Route::delete('companies/destroy/{company}', 'CompanyController@destroy')->name('companies.destroy');

##=================== Company Routes End ==========================##

##=================== Document Routes Start ==========================##

Route::get('all-documents/{company_id?}', 'DocumentController@index')->name('documents.index');
Route::post('upload-document-file', 'DocumentController@file_upload')->name('upload-document-file');
Route::post('uploaded-files-listing', 'DocumentController@list_uploaded_file')->name('uploaded-files-listing');
Route::get('download-file/{file}', 'DocumentController@download_file')->name('download-file');

Route::get('deleting-file/{id}/{userID}/{companyID}', 'DocumentController@deleting_file')->name('deleting-file');

##=================== Document Routes End ==========================##

##=================== Vehicle Routes Start ==========================##

Route::get('vehicles/create', 'VehicleController@create')->name('vehicles.create');
Route::post('vehicles', 'VehicleController@store')->name('vehicles.store');
Route::get('vehicles/{vehicle}/edit', 'VehicleController@edit')->name('vehicles.edit');
Route::post('update-vehicle', 'VehicleController@update')->name('vehicles.update');

##=================== Vehicle Routes End ==========================##

##=================== File Upload Routes Start ==========================##

Route::get('files-upload', 'FileUploadController@create')->name('files.upload');
Route::post('save-files', 'FileUploadController@store')->name('files.store');

##=================== File Upload Routes End ==========================##

##=================== File Upload Routes End ==========================##

Route::any('/assignments/create', 'AssignmentController@create')->name('assignments.create');
Route::post('/assignments', 'AssignmentController@store')->name('assignments.store');

##=================== File Upload Routes End ==========================##

##================================ RequestAccount Routes Start =============================##

Route::get('account/create', 'RequestAccountController@create')->name('request-account');
Route::post('account/create', 'RequestAccountController@store');

##================================ RequestAccount Routes End =============================##


Route::get('dropzone', 'FileUploadController@dropzone');
Route::post('store', 'FileUploadController@dropzoneStore')->name('store');

##================================ Portfolio Screen Start =============================## 
Route::any('portfolio', 'AssignmentController@portfolio')->name('portfolio'); 
Route::get('portfolio-detail/{id?}', 'AssignmentController@portfolio_vehicle_dt')->name('portfolio-detail');
Route::post('portfolio-detail', 'AssignmentController@storeportfolio')->name('portfolio-detail.storeportfolio');
Route::post('update-document', 'AssignmentController@update_document')->name('portfolio-detail.uploadDocument');
##================================ Portfolio Screen Routes End =============================##

Route::get('/redirect', 'SocialAuthGoogleController@redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback');

Route::get('/set-cron-files', 'CronJobsController@fetchFile');

## our app to Caprock export route 
Route::any('/export-to-caprock', 'ExportController@export_to_caprock');
Route::any('/assignment-export', 'ExportController@assignment_export')->name('assignment-export');
Route::any('/export-data', 'ExportController@export_xls')->name('export-data');
Route::get('users-chart', 'UserChartController@index');
Route::get('bar-chart', 'ChartController@index');

## dashboard Graphs
Route::any('dashboard', 'DashboardController@index');
 
## file send from app to caprock 
Route::get('send-file-to-caprock', 'UploadfileController@job_export_upl_file_to_caprock');

##dashboard export 
Route::any('dashboard-export-csv', 'DashboardController@dashboard_export_xls');

##dashboard export 
Route::any('title-not-rec', 'DashboardController@export_title_not_received');


##Notes Email
Route::any('notes-mail', 'AssignmentController@profile_vehicle_notes_mail');

## dashboard export and download data
Route::any('download-client-assgnmt-xls', 'DashboardController@download_client_assgnmt_xls');

##dashboard export 
Route::any('inventory-export', 'DashboardController@inventory_dashboard_export_xls');

## dashboard export and auction report download data
Route::any('export-auction-report', 'DashboardController@export_xls_last_two_days_auction');
Route::any('export-agent-report', 'DashboardController@export_xls_last_two_days_agent');
/* files url from public folder
	step1- FIrst we hit url -- import file to  importing files from caprock to our Server
	 http://devapp21.onlineorderalert.com/import_files.php
	 
	 Then through cron and job queue we import the db
	step2- http://devapp21.onlineorderalert.com/set-cron-files
	
	Then Artisan command: php artisan queue:work
	 
	 http://devapp21.onlineorderalert.com/upload_caprock_to_app_files.php*/

app/User.php
<?php

namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Lab404\Impersonate\Models\Impersonate;

class User extends Authenticatable
{   use Impersonate;
    use Notifiable;
    use CanResetPassword;
    use HasRoles;
    
   

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','fk_company_id','created_by'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
    
}

app/Http/Controllers/UserController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Arr;
use App\User;
use Spatie\Permission\Models\Role;
use DB;
use Hash;
use Auth;
use DataTables;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('permission:user-list|user-create|user-edit|user-delete', ['only' => ['index','show']]);
        $this->middleware('permission:user-create', ['only' => ['create','store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {  //  echo '<pre>ss';print_r($request->post('srchFld'));exit;
        $session_data       = get_session_data();## Helper function fetching all session data
        $current_role_id    = get_role_id();
        
         $srch = $request->post('srchFld') ; 
        $data = DB::table('users')
            ->leftJoin('companies', 'users.fk_company_id', '=', 'companies.id')
            ->select('users.*','companies.company_name');

        if(!empty($srch)){
            $data = $data->whereRaw(" (companies.company_name LIKE '%".$srch."%' OR users.name LIKE '%".$srch."%')");
        }
        if ($current_role_id>1) {
            $data = $data->where('users.created_by', $session_data['user_id']);
        }else{ 
            $data = $data->where('users.id', '<>', $session_data['user_id']);
        } 
        $data = $data->orderBy('users.id', 'DESC')->paginate(5);
 
        return view('users.index', compact('data'))->with('i', ($request->input('page', 1) - 1) * 5);
    }
    public function index2(Request $request)
    {
        if ($request->ajax()) {
            $data = User::latest()->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function ($row) {
                        $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm">View</a>';
     
                        return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
      
        return view('users');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $session_data       = get_session_data();## Helper functionfetching all session data
        $roles  = array();
        // echo '<pre>';print_r(  $session_data);exit;
        $rolesArr = DB::table('model_has_roles')->where('model_id', $session_data['user_id'])->get()->toArray();
      
        //echo '***'; dd(Auth::user() ->roles ->pluck('id') ->toArray() );;exit;
        
        $roles_arr = json_decode(json_encode($rolesArr), true);    //  echo '<pre>';print_r($rolesArr);exit;
        if ($roles_arr[0]['role_id']<='2') {
            $array = array(4);
            if ($roles_arr[0]['role_id']==1) {
                $array = array(1,2);//// FOr Display User place ",4"
            }
            $roles = Role::whereIn('id', $array);
            
            $roles = $roles->pluck('name', 'name')->all();
        }
        // echo '<pre>';print_r( $roles);exit;
        return view('users.create', compact('roles'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   //echo '<pre>';print_r($_POST);exit;
        $this->validate($request, [
            'name' => 'required',
            'roles.*' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ], ['roles.*.required'=>"Role is mandatory"]);


        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        //echo '<pre>';print_r($input);exit;
    
        $user = User::create($input);
        $rolesDt = $user->assignRole($request->input('roles'));
        return redirect()->route('users.index')
                        ->with('success', 'User created successfully');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show', compact('user'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        //$roles = Role::where('id','<>',1)->pluck('name','name')->all();

        $session_data       = get_session_data();## Helper functionfetching all session data
 
         
        $roles = Role::pluck('name', 'name')->all();
        
        $userRole = $user->roles->pluck('name', 'name')->all();
        //dd($userRole);
        return view('users.edit', compact('user', 'roles', 'userRole'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            //'roles' => 'required'
        ]);


        $input = $request->all();
        if (!empty($input['password'])) {
            $input['password'] = Hash::make($input['password']);
        } else {
            $input = Arr::except($input, array('password'));
        }


        $user = User::find($id);
        $user->update($input);
        //DB::table('model_has_roles')->where('model_id', $id)->delete();


        //$user->assignRole($request->input('roles'));


        return redirect()->route('users.index')
                        ->with('success', 'User updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $session_data       = get_session_data();## Helper functionfetching all session data
        if ($id!=1 && $id!= $session_data['user_id']) {
            User::find($id)->delete();
        }
        return redirect()->route('users.index')
                        ->with('success', 'User deleted successfully');
    }

    public function impersonate($user_id)
    {
        if ($user_id != ' ') {
            $user = User::find($user_id);
            Auth::user()->impersonate($user);
            return redirect('/');
        }
        return redirect()->back();
    }

    public function impersonate_leave()
    {
        Auth::user()->leaveImpersonation();
        return redirect('/');
    }

    public function user_profile(User $user)
    {
        return view('users.my_profile', compact('user'));
    }
}

resources/views/users/create.blade.php
@extends('layouts.master')
@section('content')
<!---- Form Section ---->
<section class="content">
  <div class="container-fluid">

    <div class="card card-default" style="box-shadow:none;">


      <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-5">
          <h2>Create New User</h2>
        </div>
        <div class="col-md-1" style="padding-left:4%"> <a class="btn btn-primary" href="{{ route('users.index') }}">
            Back</a></div>
      </div>


      <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-6">
          @if (count($errors) > 0)
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif
        </div>
      </div>
      {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
      <div class="row">
        <div class="col-md-3"> &nbsp;</div>
        <div class="col-md-6">
          <div class="card card-danger">
            <div class="card-header bg-caprock-col" >
              <h3 class="card-title">Register User</h3>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label>Name:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">@</i></span>
                  </div>
                  {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

                </div>
              </div>
              <div class="form-group">
                <label>Email:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                  </div>
                  {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                </div>
              </div>
              <div class="form-group">
                <label>Password</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">#</span>
                  </div>
                  {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                </div>
              </div>
              <div class="form-group">
                <label>Confirm Password:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">##</span>
                  </div>
                  {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' =>
                  'form-control')) !!}
                </div>
              </div>
              @php $listComp = company_listing();
              $session_data = get_session_data();## Helper functionfetching all session data
              $user_id = $session_data['user_id'];
              $fk_company_id =$session_data['fk_company_id'];
              $user_role='';               
              $currentuser = Auth::user() ->getRoleNames();
              if(count($currentuser)>0){
                $user_role = $currentuser[0];
              }
             // echo '<pre>';print_r( $currentuser);exit;
              //echo '****'.$currentuser ->getRoleNames();
              @endphp

              <div class="form-group">
                              
                <label>Role:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-laptop"></i></span>
                  </div> 
                  @if($user_role=='Caprock Administrator')
                  {!! Form::select('roles[]', array_merge(['' => 'Please Select'], $roles),[], array('class' => 'form-control','onchange'=>"return change_company_opt(this.value);")) !!}
                  @else
                  {!! Form::select('roles[]', $roles,[], array('class' => 'form-control')) !!}
                  @endif
                </div>
              </div>

              @if($user_role=='Caprock Administrator')
              <div class="form-group" id="company_div">
                <label>Company:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-laptop"></i></span>
                  </div>
                  {!! Form::select('fk_company_id', $listComp, '--', ['class' => 'form-control']) !!}
                </div>
              </div>
              @else
              {!! Form::hidden('fk_company_id', "$fk_company_id", array()) !!}

              @php
              $comp_dt = company_listing($fk_company_id);
              if($comp_dt){
              $compArr = array_values($comp_dt->toArray());
              $comp_name = $compArr;
              }
              @endphp
              <div class="form-control"><b>{{ ucwords(@$comp_name[0]) }}</b> </div>
              @endif

              
              <div class="">
                {!! Form::hidden('created_by', $user_id, array('placeholder' => 'created_by','class' => 'form-control'))
                !!}
                <button type="submit" class="btn btn-info">Submit</button> 
                <a href="" class="btn btn-info float-right">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {!! Form::close() !!}
    </div>
</section>
 
<script>
  function change_company_opt(val){ 
    $("#company_div").show();
   if(val=='Caprock Administrator'){
      $("#company_div").hide();
   }

  }
  change_company_opt( "<?php echo @old('roles')[0];?>")
</script>
<!---- Form Section ---->


@endsection

resources/views/users/index.blade.php
@extends('layouts/master')
@section('content')

<div class="section_wrapper mcb-section-inner"> 
  <div class="form-group row">
    <div class="col-lg-12 margin-tb alert alert-danger bg-caprock-col">      
      <div class="col-md-4 pull-left">
        <h3>User Management</h3>
      </div>
      <div class="col-md-5 pull-left">
        <form action="{{ route('users.index') }}" method="get" id="user_frm_srch">
        
          @csrf
          <div class="form-group row">
            <div class="input-group col-md-8">
                <div class="input-group-prepend">
                  <span class="input-group-text"><i class="fas fa-search"></i></i></span>
                </div>
               <input type="text" placeholder="Search Name or Company" value="<?php echo @$_REQUEST['srchFld']?>" class="form-control" name="srchFld" id="srchFld"> 
            </div> 
             
          </div>
        </form>
      </div>
      <div class="col-md-2 pull-left">
        @if(session('impersonated_by') )
        <a class="link_btn pull-left" style="text-decoration:none;" href="<?php echo url('impersonate_leave') ;?>">Back to my account</a>
        @else
        <!-- <li> <a class="btn btn-info" href="{{ route('logout') }}">Logout</a></li>  --> 
        @endif</div>

      <div class="col-md-1 pull-right">
        @can('user-create')
        <div class=" link_btn"> 
        <a href="{{ route('users.create') }}"> Create User</a>
        </div>
        @endcan
      </div>
    </div>
  </div>
<?php 
$session_data = get_session_data();

//echo '<pre>';print_r($session_data['role_name']);exit;
?>

  @if ($message = Session::get('success'))
  <div class="alert alert-success">
    {{ $message }} 
  </div>
  @endif

  <table class="table table-bordered text-left">
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Email</th>
      <th>Associated Company</th>
      <th>Role</th> 
      <th width="20%">Login as </th>
      <th width="20%">Action</th>
    </tr>
    @if(count($data)>0)
      @foreach ($data as $key => $user)
      <?php  
      $userRoleName =  App\User::find($user->id)->getRoleNames() ; 

       //$user = json_decode(json_encode($user),true);
      // echo '<pre>';print_r($user);exit;
       $company_name = '';
      if(@$userRoleName[0]!='Caprock Administrator'){ 
        $fk_company_id =$user->fk_company_id; 
        $compaData = company_listing($fk_company_id); 
      
        if($compaData){
          @$compaDataArr = $compaData->toArray(); 
          @$company_name  = array_values( @$compaDataArr )[0];  
        }
      }
     
      ?>
      @if($user->id!=$session_data['user_id'])
      <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
        <td>{{ $company_name }}</td>
        <td>
          <?php  $userRoleName2 =  App\User::find($user->id)->getRoleNames() ; ?>
          @if(@$userRoleName[0]!='')
          @foreach($userRoleName2 as $v)
          <span class="client_name">{{ $v }}</span> 
          @endforeach
          @endif
        </td>
        <td> 
          @if(!empty($user->id))
          <a class="btn btn-sm btn-success" href="<?php echo url('impersonate/'.$user->id) ;?>" data-toggle='tooltip'
            data-placement='top' title='Impersonate'>login as {{ $v }}</a>
          @endif
         
        </td>
        <td>
          <div class="row">
            <div class="col-md-3">
              @can('user-show')
              <a class="btn btn-sm btn-info pull-left" href="{{ route('users.show',$user->id) }}"><i class="fas fa-eye"></i></a>
              @endcan
            </div>
            <div class="col-md-3">
              @can('user-edit')
              <a class="btn btn-sm btn-primary" href="{{ route('users.edit',$user->id) }}"><i class="fas fa-edit"></i></a>
              @endcan
            </div>
            <div class="col-md-3">
              @can('user-delete')
            <form action="{{ route('users.destroy', $user->id) }}" method="post" id="frm_{{$user->id}}">
                @csrf
                @method('delete')
                <button class="btn btn-sm btn-primary"  onclick="return deleteUser('<?php echo $user->id ?>');" type="submit"><i class="fa fa-trash" aria-hidden="true"></i></button>
              </form>
              {{-- {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
              {!! Form::submit('Delete', ['class' => 'btn btn-sm btn-danger pull-right']) !!}
              {!! Form::close() !!} --}}
              @endcan
            </div>
          </div>
        </td>
      </tr>
      @endif
      @endforeach
    @else
    <tr>
        <td colspan="8" style="color:red;text-align:center !important;">No Data Found </td>
         
  </tr>
    @endif
  </table>
<script>
function deleteUser(id){ 
    var r = confirm("Are you sure to delete company?");
    if (r == true) {
      $("#frm_"+id).submit(); 
    } else {
      return false;
    }
  }
  </script>
 {{ $data->appends(Request::except('page'))->links() }}
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts/master')
@section('content')
<div class="section_wrapper mcb-section-inner">
 
 

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<?php //echo '<pre>';print_r($roles);exit;?>

<div class="row">
      <div class="col-md-2"> &nbsp;</div>
      <div class="col-md-8">
        <div class="card card-danger">
           


            <div class="form-group row">
                <div class="col-lg-12 margin-tb alert alert-danger bg-caprock-col">
                  
                  <div class="col-md-4 pull-left">
                    <h3>Show User Detail</h3>
                  </div>
                  <div class="col-md-2 pull-left ">
                    @if(session('impersonated_by') )
                    <a class=" pull-left link_btn" style="text-decoration:none;" href="<?php echo url('impersonate_leave') ;?>">Back to my  account</a>  
                   @endif
                    </div>
                   &nbsp;
                  <div class="col-md-3 pull-left link_btn" style="text-align:center;"> 
                    @can('user-create')
                    <a class=" " style="text-decoration:none;" href="{{ route('users.create') }}">Create New User</a>
                    @endcan
                  </div>
                  &nbsp; <div class="col-md-1 pull-right link_btn" style="text-align:center;"> 
                    @can('user-create')
                    <a class=" " style="text-decoration:none;" href="{{ route('users.index') }}">Back</a>
                    @endcan
                  </div>
                 
                         
                </div>
              </div>


              
           
          <div class="card-body">
            
              <label>Name:</label> {{ $user->name }}</div>             
          

          <div class="card-body">
           
              <label>Email:</label> {{ $user->email }}         
          </div>

           


        </div>
      </div>
    </div>

</div></div>
   <style>.card-body{padding:0.5rem;}</style>
    @endsection