routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cache-clear', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    return Redirect::to('/');
});

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('logout', function () {
    Auth::logout();
    return Redirect::to("/login")
      ->with('message', array('type' => 'success', 'text' => 'You have successfully logged out'));
});

Route::get('/', function () {
    Auth::logout();
    return Redirect::to("/login")
      ->with('message', array('type' => 'success', 'text' => 'You have successfully logged out'));
});
 
Route::get('/home', 'UserController@index')->name('/');


Auth::routes();

Route::get('/forgot-password', function () {
    return view('auth.forgot-password');
})->middleware(['guest'])->name('password.request');

Route::post('/forgot-password', 'ForgotPasswordController@sent_reset_email')->middleware(['guest'])->name('password.email');

Route::get('/password/reset/{token}', function ($token) {
    return view('auth.reset-password', ['token' => $token]);
})->middleware(['guest'])->name('password.reset');

Route::post('/reset-password', 'ForgotPasswordController@reset_password')->middleware(['guest'])->name('password.update');

Route::get('/roles', 'RoleController@index')->name('roles');

Route::any('users', 'UserController@index')->name('users.index');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('products', 'ProductController');
});

Route::get('impersonate/{user_id}', 'RoleController@impersonate');
Route::get('impersonate_leave', 'RoleController@impersonate_leave');

##=================== Company Routes Start ==========================##

Route::any('companies', 'CompanyController@index')->name('companies.index');
Route::get('companies/create/{company?}', 'CompanyController@create')->name('companies.create');
Route::post('companies/store', 'CompanyController@store')->name('companies.store');
Route::get('companies/show/{company}', 'CompanyController@show')->name('companies.show');
Route::get('companies/edit/{company}', 'CompanyController@edit')->name('companies.edit');
Route::post('companies/update/{company}', 'CompanyController@update')->name('companies.update');
Route::delete('companies/destroy/{company}', 'CompanyController@destroy')->name('companies.destroy');

##=================== Company Routes End ==========================##

##=================== Document Routes Start ==========================##

Route::get('all-documents/{company_id?}', 'DocumentController@index')->name('documents.index');
Route::post('upload-document-file', 'DocumentController@file_upload')->name('upload-document-file');
Route::post('uploaded-files-listing', 'DocumentController@list_uploaded_file')->name('uploaded-files-listing');
Route::get('download-file/{file}', 'DocumentController@download_file')->name('download-file');

Route::get('deleting-file/{id}/{userID}/{companyID}', 'DocumentController@deleting_file')->name('deleting-file');

##=================== Document Routes End ==========================##

##=================== Vehicle Routes Start ==========================##

Route::get('vehicles/create', 'VehicleController@create')->name('vehicles.create');
Route::post('vehicles', 'VehicleController@store')->name('vehicles.store');
Route::get('vehicles/{vehicle}/edit', 'VehicleController@edit')->name('vehicles.edit');
Route::post('update-vehicle', 'VehicleController@update')->name('vehicles.update');

##=================== Vehicle Routes End ==========================##

##=================== File Upload Routes Start ==========================##

Route::get('files-upload', 'FileUploadController@create')->name('files.upload');
Route::post('save-files', 'FileUploadController@store')->name('files.store');

##=================== File Upload Routes End ==========================##

##=================== File Upload Routes End ==========================##

Route::any('/assignments/create', 'AssignmentController@create')->name('assignments.create');
Route::post('/assignments', 'AssignmentController@store')->name('assignments.store');

##=================== File Upload Routes End ==========================##

##================================ RequestAccount Routes Start =============================##

Route::get('account/create', 'RequestAccountController@create')->name('request-account');
Route::post('account/create', 'RequestAccountController@store');

##================================ RequestAccount Routes End =============================##


Route::get('dropzone', 'FileUploadController@dropzone');
Route::post('store', 'FileUploadController@dropzoneStore')->name('store');

##================================ Portfolio Screen Start =============================## 
Route::any('portfolio', 'AssignmentController@portfolio')->name('portfolio'); 
Route::get('portfolio-detail/{id?}', 'AssignmentController@portfolio_vehicle_dt')->name('portfolio-detail');
Route::post('portfolio-detail', 'AssignmentController@storeportfolio')->name('portfolio-detail.storeportfolio');
Route::post('update-document', 'AssignmentController@update_document')->name('portfolio-detail.uploadDocument');
##================================ Portfolio Screen Routes End =============================##

Route::get('/redirect', 'SocialAuthGoogleController@redirect');
Route::get('/callback', 'SocialAuthGoogleController@callback');

Route::get('/set-cron-files', 'CronJobsController@fetchFile');

## our app to Caprock export route 
Route::any('/export-to-caprock', 'ExportController@export_to_caprock');
Route::any('/assignment-export', 'ExportController@assignment_export')->name('assignment-export');
Route::any('/export-data', 'ExportController@export_xls')->name('export-data');
Route::get('users-chart', 'UserChartController@index');
Route::get('bar-chart', 'ChartController@index');

## dashboard Graphs
Route::any('dashboard', 'DashboardController@index');
 
## file send from app to caprock 
Route::get('send-file-to-caprock', 'UploadfileController@job_export_upl_file_to_caprock');

##dashboard export 
Route::any('dashboard-export-csv', 'DashboardController@dashboard_export_xls');

##dashboard export 
Route::any('title-not-rec', 'DashboardController@export_title_not_received');


##Notes Email
Route::any('notes-mail', 'AssignmentController@profile_vehicle_notes_mail');

## dashboard export and download data
Route::any('download-client-assgnmt-xls', 'DashboardController@download_client_assgnmt_xls');

##dashboard export 
Route::any('inventory-export', 'DashboardController@inventory_dashboard_export_xls');

## dashboard export and auction report download data
Route::any('export-auction-report', 'DashboardController@export_xls_last_two_days_auction');
Route::any('export-agent-report', 'DashboardController@export_xls_last_two_days_agent');
/* files url from public folder
	step1- FIrst we hit url -- import file to  importing files from caprock to our Server
	 http://devapp21.onlineorderalert.com/import_files.php
	 
	 Then through cron and job queue we import the db
	step2- http://devapp21.onlineorderalert.com/set-cron-files
	
	Then Artisan command: php artisan queue:work
	 
	 http://devapp21.onlineorderalert.com/upload_caprock_to_app_files.php*/

app/Product.php
<?php 
namespace App; 
use Illuminate\Database\Eloquent\Model; 
class Product extends Model{
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'name', 'detail'
    ];
}

app/Http/Controllers/ProductController.php
<?php 
namespace App\Http\Controllers; 
use App\Product;
use Illuminate\Http\Request;
use Impersonate; 

class ProductController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show']]);
         $this->middleware('permission:product-create', ['only' => ['create','store']]);
         $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:product-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(5);
        return view('products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);


        Product::create($request->all());


        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
         request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);


        $product->update($request->all());


        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();


        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }

    
}

resources/views/products/create.blade.php
@extends('layouts.master')
@section('content')
<!---- Form Section ---->
<section class="content">
  <div class="container-fluid">

    <div class="card card-default" style="box-shadow:none;">

      <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-5">
          <h2>Create New Product</h2>
        </div>
        <div class="col-md-1"> <a class="btn btn-primary" href="{{ route('products.index') }}">
            Back</a></div>
      </div>

      <div class="row">
        <div class="col-md-3">&nbsp;</div>
        <div class="col-md-6">
          @if (count($errors) > 0)
          <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif
        </div>
      </div>
      {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}
      <div class="row">
        <div class="col-md-3"> &nbsp;</div>
        <div class="col-md-6">
          <div class="card card-warning">
            <div class="card-header">
              <h3 class="card-title">Register User</h3>
            </div>
            <div class="card-body">
              <div class="form-group">
                <label>Name:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">@</i></span>
                  </div>
                  {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}

                </div>
              </div>
              <div class="form-group">
                <label>Email:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                  </div>
                  {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}
                </div>
              </div>
              <div class="form-group">
                <label>Password</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">#</span>
                  </div>
                  {!! Form::password('password', array('placeholder' => 'Password','class' => 'form-control')) !!}
                </div>
              </div>
              <div class="form-group">
                <label>Confirm Password:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">##</span>
                  </div>
                  {!! Form::password('confirm-password', array('placeholder' => 'Confirm Password','class' =>
                  'form-control')) !!}
                </div>
              </div>


              <div class="form-group">
                <label>Role:</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-laptop"></i></span>
                  </div>
                  {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}
                </div>
              </div>
              <div class="card-footer">
                {!! Form::text('created_by', $user_id, array('placeholder' => 'created_by','class' => 'form-control'))
                !!}
                <button type="submit" class="btn btn-info">Submit</button>
                <button type="submit" class="btn btn-default float-right">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      {!! Form::close() !!}
    </div>
</section>
<!---- Form Section ---->


@endsection

resources/views/products/edit.blade.php
@extends('layouts.master') 
@section('content') 
 <!---- Form Section ---->
 <section class="content"> 
<div class="container-fluid">
    
  <div class="card card-default" style="box-shadow:none;">

 <div class="row">
 <div class="col-md-3">&nbsp;</div> 
 <div class="col-md-6">
 @include('layouts/auth_links')
 </div>
 </div>

 <div class="row">
 <div class="col-md-3">&nbsp;</div> 
 <div class="col-md-5"><h2>Update product</h2></div>
 <div class="col-md-1" style="padding-left:4%"> <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a></div> 
 </div>
 
  
 <div class="row">
 <div class="col-md-3">&nbsp;</div> 
 <div class="col-md-6">   
 @if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif
 </div>
 </div>
 <form action="{{ route('products.update',$product->id) }}" method="POST">
    
    <div class="row">
      <div class="col-md-3"> &nbsp;</div>
      <div class="col-md-6">
        <div class="card card-warning">
          <div class="card-header">
            <h3 class="card-title">Update Product</h3>
          </div>
          <div class="card-body">
            <div class="form-group">
              <label>Name:</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">@</i></span>
                </div>
                <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
                
               
              </div>
            </div>
            <div class="form-group">
            <label>Details:</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text">--</span>
                </div>
                <input type="text" name="detail" value="{{ $product->detail }}" class="form-control" placeholder="Name">
      
              </div>
            </div>
            
             
            <div class="card-footer">
             
              <button type="submit" class="btn btn-info">Submit</button>
              <button type="submit" class="btn btn-default float-right">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>
    {!! Form::close() !!}
  </div>
</section>
<!---- Form Section ---->
 
 
@endsection

resources/views/products/index.blade.php
@extends('layouts.master')
@section('content') 
<div class="section_wrapper mcb-section-inner">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="col-md-4">&nbsp;</div>
        <div class="col-md-8">
        @include('layouts/auth_links')
        </div>
         
    </div>
</div>

<div class="section_wrapper mcb-section-inner"> 
  <div class="row">
    <div class="col-lg-12 margin-tb">
      <div class="col-md-4">&nbsp;</div>
      <div class="col-md-4 pull-left">
        <h2>Products</h2>
      </div>
      <div class="col-md-3 pull-left">
        @if(session('impersonated_by') )
        <a class="alert alert-info pull-left" href="<?php echo url('impersonate_leave') ;?>">Back to my account</a>
        @else
        <!-- <li> <a class="btn btn-info" href="{{ route('logout') }}">Logout</a></li>  -->
        @endif</div>


      <div class="pull-right">
        @can('product-create')
        <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
        @endcan
      </div>
    </div>
  </div>


  @if ($message = Session::get('success'))
  <div class="alert alert-success">
    <p>{{ $message }}</p>
  </div>
  @endif


  <table class="table table-bordered">
    <tr>
      <th>No</th>
      <th>Name</th>
      <th>Details</th>
      <th width="280px">Action</th>
    </tr>
    @foreach ($products as $product)
    <tr>
      <td>{{ ++$i }}</td>
      <td>{{ $product->name }}</td>
      <td>{{ $product->detail }}</td>
      <td>
        <form action="{{ route('products.destroy',$product->id) }}" method="POST">
          <a class="btn btn-info" href="{{ route('products.show',$product->id) }}">Show</a>
          @can('product-edit')
          <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">Edit</a>
          @endcan


          @csrf
          @method('DELETE')
          @can('product-delete')
          <button type="submit" class="btn btn-danger">Delete</button>
          @endcan
        </form>
      </td>
    </tr>
    @endforeach
  </table>


  {!! $products->links() !!}





</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts/master')
@section('content')
<div class="section_wrapper mcb-section-inner">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="col-md-4">&nbsp;</div>
        <div class="col-md-8">
        @include('layouts/auth_links')
        </div>
         
    </div>
</div>


<div class="row">
    <div class="col-lg-12 margin-tb">
    <div class="col-md-4">&nbsp;</div>
        
        <div class="col-md-3 pull-left">
    @if(session('impersonated_by') )
     <a class="alert alert-info pull-left" href="<?php echo url('impersonate_leave') ;?>">Back to my  account</a> 
    @else
    <!-- <li> <a class="btn btn-info" href="{{ route('logout') }}">Logout</a></li>  -->
    @endif</div>
        <div class="pull-right">
            @can('role-create')
            <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
            @endcan
        </div>
        
    </div>
</div>


@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif
<?php //echo '<pre>';print_r($roles);exit;?>

<div class="row">
      <div class="col-md-3"> &nbsp;</div>
      <div class="col-md-6">
        <div class="card card-warning">
          <div class="card-header">
            <h3 class="card-title">Show Product Detail</h3>
          </div>
          <div class="card-body">
            
              <label>Name:</label>  {{ $product->name }}</div>             
          

          <div class="card-body">
           
              <label>Email:</label>  {{ $product->detail }}     
          </div>

           


        </div>
      </div>
    </div>

</div></div>
   <style>.card-body{padding:0.5rem;}</style>
    @endsection